adminpage/urls.py
from django.urls import path, include
from adminpage import views

app_name = 'adminpage'

urlpatterns = [
    path('', views.Admin_Home.as_view(), name='admin_home'),
    path('get_grade_data/', views.Admin_Home.as_view(), name='get_grade_data'),

    path('adminpage/user_manage/', views.User_Manage.as_view(), name='user_index'),
    path('update_user_authority/', views.update_user_authority, name='update_user_authority'),

    # 원시
    path('adminpage/wonsi_verification/', views.Wonsi_Verification.as_view(), name='wonsi_verification_index'),
    path('update_wonsi_verification/', views.update_wonsi_verification, name='update_wonsi_verification'),
    path('adminpage/wonsi_verification/<int:pk>/', views.wonsi_data_detail, name='wonsi_data_detail'),

    # 라벨링
    path('adminpage/data_labeling_verification/', views.Data_labeling_Verification.as_view(), name='data_labeling_verification_index'),
    path('update_data_labeling_verification/', views.update_data_labeling_verification, name='update_data_labeling_verification'),
    path('adminpage/data_labeling_verification/<int:pk>/', views.labeling_data_detail, name='labeling_detail'),
    path('adminpage/assignment/', views.assignment_view, name='assignment_view'),
    path('adminpage/assign_data/', views.assign_data, name='assign_data'),

    # adminnotice
    path('adminpage/adminnotice/', views.notice_index, name='notice_index'),
    path('adminpage/adminnotice/new/', views.notice_NewView, name='notice_new'),
    path('adminpage/adminnotice/create/', views.notice_Create, name='notice_create'),
    path('adminpage/adminnotice/<int:pk>/', views.notice_Detail, name='notice_detail'),
    path('adminpage/adminnotice/<int:pk>/delete/', views.notice_delete, name='notice_delete'),
    path('adminpage/adminnotice/<int:pk>/edit/', views.notice_edit, name='notice_edit'),
    path('adminpage/adminnotice/<int:pk>/update/', views.notice_update, name='notice_update'),

    # questionboardadmin
    path('adminpage/questionboardadmin/', views.questionboard_index, name='questionboard_index'),
    path('adminpage/questionboardadmin/<int:pk>/', views.questionboard_Detail, name='questionboard_detail'),
    path('adminpage/questionboardadmin/<int:pk>/delete/', views.questionboard_delete, name='questionboard_delete'),

    # 포인트

    path('point_d_list/', views.show_point_d_list, name='point_d_list'),
    path('adminpage/point_change/', views.point_change_form, name='point_change'),
    path('point_change/', views.point_change_form, name='point_change_form'),
    path('adminpage/Point_settlement_list/', views.Point_settlement_index, name='Point_settlement_list'),
    path('update_data_Point_settlement/', views.update_data_Point_settlement, name='update_data_Point_settlement'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('startpage.urls')),
    path('home/', include('uploadpage.urls', namespace='uploadpage')),
    path('home/', include('adminpage.urls', namespace='adminpage')),
    path('home/', include('notice.urls', namespace='notice')),
    path('home/', include('questionboard.urls', namespace='questionboard')),
    path('home/', include('labelingpage.urls', namespace='labelingpage')),
    path('home/', include('my_page.urls', namespace='my_page')),
    path('home/', include('yolov8.urls', namespace='yolov8')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminpage/models.py
from django.db import models

from Account.models import UserInfo


class PointSetting(models.Model):
    label_point = models.PositiveIntegerField()
    upload_point = models.PositiveIntegerField()

    class Meta:
        db_table = 'point_setting'

class Admin(models.Model):
    admin_id = models.CharField(max_length=50, primary_key=True)
    pwd = models.CharField(max_length=50)

    class Meta:
        db_table = 'admin'


class point_A(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='중복제거')
    user_name = models.CharField(max_length=20, null=False, verbose_name='유저 아이디')
    remaining_points = models.IntegerField(default=0, verbose_name='남은 포인트')

    class Meta:
        db_table = 'point_a'
        indexes = [
            models.Index(fields=['user_name']),
        ]
        verbose_name = '유저의 남은 포인트 조회하는 테이블'
        verbose_name_plural = '유저의 남은 포인트 조회하는 테이블'

class point_B(models.Model):
    point_num = models.IntegerField(primary_key=True, verbose_name='중복제거')
    user_name = models.CharField(max_length=20, null=False, verbose_name='지급 유저')
    point_version = models.IntegerField(null=False, verbose_name='작업 환경(1원시 2라벨)')
    point_pay = models.IntegerField(null=False, verbose_name='지급 포인트')
    point_date = models.DateField(null=False, verbose_name='지급 일자')

    class Meta:
        db_table = 'point_b'
        indexes = [
            models.Index(fields=['user_name']),
        ]
        verbose_name = '포인트 지급 테이블 (원시 / 라벨링 데이터 검증되면 포인트(로그) 지급됨)'

class point_C(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='중복제거')
    point_version = models.IntegerField(null=False, verbose_name='변경하는 포인트 (1 원시 2라벨링)')
    point_pay = models.IntegerField(null=False, verbose_name='변경하는 가격')
    point_date = models.DateField(null=False, verbose_name='변경일자')

    class Meta:
        db_table = 'point_c'
        verbose_name = '포인트 가격 조정하는 테이블'


class point_D(models.Model):
    money_num = models.IntegerField(primary_key=True, verbose_name='중복제거')
    money_Payments = models.IntegerField(null=False, verbose_name='전환 가격')
    money_date = models.DateField(null=False, verbose_name='요청일자')
    money_a = models.IntegerField(null=False, verbose_name='상태(0 대기 1 지급 2반환)')
    user_name = models.CharField(max_length=20, null=False, verbose_name='요청 유저')

    class Meta:
        db_table = 'point_d'
        indexes = [
            models.Index(fields=['user_name']),
        ]
        verbose_name = '포인트 현금 전환 로그 테이블'

adminpage/views.py
import ast
from datetime import timedelta

from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.views import View
from django.views.generic import ListView
from Account.models import UserInfo
from django.urls import reverse
from django.db.models import Sum
from questionboard.models import QuestionBoard,Answer
from uploadpage.models import WonsiData, WonsiBoard, WonsiComments
from labelingpage.models import LabelingBoard, LabelingComments
from adminpage.models import Admin
from notice.models import Notice
from django.conf import settings
from google.cloud import storage
from django.shortcuts import render
from collections import Counter
import json
from django.http import JsonResponse

from adminpage.models import point_A
from adminpage.models import point_B
from adminpage.models import point_C
from adminpage.models import point_D

class Admin_Home(View):
    def get(self, request):
        user_data = UserInfo.objects.values('authority').annotate(total=Count('authority'))
        user_data_json = json.dumps(list(user_data))

        user_info = UserInfo.objects.get(username=request.user)
        if user_info.authority not in [4, 5]:
            return render(request, 'access_denied.html')
        else:
            total_veri_sum = WonsiData.objects.aggregate(Sum('wonsi_verification'))['wonsi_verification__sum']
            total_label_sum = LabelingData.objects.aggregate(Sum('label_verification'))['label_verification__sum']
            waiting_sum = point_D.objects.filter(money_a=0).aggregate(sum=Sum('money_Payments'))['sum']
            settlement_sum = point_D.objects.filter(money_a=2).aggregate(sum=Sum('money_Payments'))['sum']

            # 원 그래프 데이터 추가
            age_data = WonsiData.objects.values_list('age', flat=True)
            age_counts = dict(Counter(age_data))
            total = sum(age_counts.values())
            age_ratios = {age: count / total for age, count in age_counts.items()}
            age_ratios_json = json.dumps(age_ratios)

            # grade에 따른 데이터 개수 계산
            grades = WonsiData.objects.values_list('grade', flat=True).distinct()
            grade_counts = {grade: WonsiData.objects.filter(grade=grade).count() for grade in grades}
            grade_counts_json = json.dumps(grade_counts)

            today = timezone.now().date()
            # 날짜별 개수 구하기
            wonsi_data_count = WonsiBoard.objects.filter(date__gte=today - timedelta(days=6)).values('date').annotate(
                count=Count('wonsi_num'))
            labeling_data_count = LabelingBoard.objects.filter(create_date__gte=today - timedelta(days=6)).values(
                'create_date').annotate(count=Count('board_num'))

            # 날짜별 데이터를 담을 리스트를 초기화
            wonsi_data_list = []
            for data in wonsi_data_count:
                wonsi_data_list.append({
                    'date': data['date'].strftime('%Y-%m-%d'),  # 날짜 형식 변경
                    'count': data['count'],
                })

            labeling_data_list = []
            for data in labeling_data_count:
                labeling_data_list.append({
                    'date': data['create_date'].strftime('%Y-%m-%d'),  # 날짜 형식 변경
                    'count': data['count'],
                })


            context = {
                'user_data_json': user_data_json,
                'total_veri_sum': total_veri_sum,
                'total_label_sum': total_label_sum,
                'settlement_sum': settlement_sum,
                'waiting_sum': waiting_sum,
                'age_ratios_json': age_ratios_json,
                'grade_counts_json': grade_counts_json,
                'wonsi_data': json.dumps(wonsi_data_list),
                'labeling_data': json.dumps(labeling_data_list),

            }

            return render(request, 'admin_home.html', context)

    def get_grade_data(self, request):
        age = request.GET.get('age')
        grade_data = WonsiData.objects.filter(age=age).values_list('grade', flat=True)
        grade_counts = dict(Counter(grade_data))

        return JsonResponse(grade_counts)
class CommonDataMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_info = UserInfo.objects.get(username=self.request.user)
        if user_info.authority in [4, 5]:
            Point_boards_queryset = point_D.objects.all()
            Point_boards = list(Point_boards_queryset)
            waiting_sum = point_D.objects.filter(money_a=0).aggregate(sum=Sum('money_Payments'))['sum']
            settlement_sum = point_D.objects.filter(money_a=2).aggregate(sum=Sum('money_Payments'))['sum']
            total_veri_sum = WonsiData.objects.aggregate(Sum('wonsi_verification'))['wonsi_verification__sum']
            total_label_sum = LabelingData.objects.aggregate(Sum('label_verification'))['label_verification__sum']
            context.update({
                'total_veri_sum': total_veri_sum,
                'total_label_sum': total_label_sum,
                'settlement_sum': settlement_sum,
                'waiting_sum': waiting_sum,
            })

        return context

class User_Manage(CommonDataMixin,ListView):
    model = UserInfo
    template_name = 'user_manage_list.html'

    def dispatch(self, request, *args, **kwargs):
        username = request.user
        user_info = UserInfo.objects.get(username=username)
        if not username.is_authenticated or user_info.authority not in [4, 5]:
            return render(request, 'access_denied.html')
        return super().dispatch(request, *args, **kwargs)


def User_index(request):
    user_info = UserInfo.objects.get(username=request.user)
    if user_info.authority not in [4, 5]:
        return render(request, 'access_denied.html')
    else:
        all_users = UserInfo.objects.order_by("-authority")
        return render(request, 'adminpage/user_manage_list.html', {'object_list': all_users})



def update_user_authority(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        authority = request.POST.get('authority')

        user = UserInfo.objects.get(username=username)

        user.authority = authority
        user.save()

        if request.method == 'POST':
            username = request.POST.get('username')
            user_info = UserInfo.objects.get(username=username)
            if user_info.authority in [4,5]:
                admin_make = Admin.objects.create(
                    admin_id=user_info.username,
                    pwd='1234'
                )
            else:
                try:
                    admin_to_delete = Admin.objects.get(admin_id=user_info.username)
                    admin_to_delete.delete()

                except ObjectDoesNotExist:
                    pass

        return HttpResponseRedirect(reverse('adminpage:user_index'))
    else:
        return render(request, 'adminpage/user_manage_list.html')


# class Wonsi_Verification(CommonDataMixin,ListView):
#     model = WonsiBoard
#
#     template_name = 'wonsi/wonsi_verification_list.html'
#     context_object_name = 'Wonsi_List'
#
#     def dispatch(self, request, *args, **kwargs):
#         username = request.user
#         user_info = UserInfo.objects.get(username=username)
#         if not username.is_authenticated or user_info.authority not in [4, 5]:
#             return render(request, 'access_denied.html')
#         return super().dispatch(request, *args, **kwargs)
#
#     def Wonsi_verification_index(request):
#         user_info = UserInfo.objects.get(username=request.user)
#         if user_info.authority not in [4, 5]:
#             return render(request, 'access_denied.html')
#         else:
#             all_boards = WonsiBoard.objects.all().order_by("-date")
#             return render(request, 'wonsi/wonsi_verification_list.html', {'all_boards': all_boards})


from django.views.generic import ListView
from django.http import HttpResponseRedirect
class Wonsi_Verification(CommonDataMixin, ListView):
    model = WonsiBoard
    template_name = 'wonsi/wonsi_verification_list.html'
    context_object_name = 'Wonsi_List'
    paginate_by = 10

    def dispatch(self, request, *args, **kwargs):
        username = self.request.user.username
        user_info = UserInfo.objects.get(username=username)
        if not self.request.user.is_authenticated or user_info.authority not in [4, 5]:
            return render(self.request, 'access_denied.html')
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by("-date", "-wonsi_num")
        return queryset

    def post(self, request, *args, **kwargs):
        action = self.request.POST.get("action")
        if action == "filter":
            state = self.request.POST.get("state")
            if state == "all":
                queryset = WonsiBoard.objects.all()
            elif state == "processing":
                queryset = WonsiBoard.objects.filter(state=0)
            elif state == "rejected":
                queryset = WonsiBoard.objects.filter(state=2)
            elif state == "approved":
                queryset = WonsiBoard.objects.filter(state=1)
            else:
                queryset = WonsiBoard.objects.all()

            paginator = Paginator(queryset, self.paginate_by)
            page_number = self.request.GET.get('page')
            page_obj = paginator.get_page(page_number)

            context = {
                'page_obj': page_obj,
            }
            return render(self.request, 'wonsi/wonsi_verification_list.html', context)

        return HttpResponseRedirect(self.request.path)


def update_wonsi_verification(request):
    username = request.user.username
    user_info = UserInfo.objects.get(username=username)
    if user_info.authority not in [4, 5]:
        return render(request, 'access_denied.html')
    else:

adminpage/templates/questionboardadmin/questionboard_admin_detail.html
{% extends "admin_base.html" %}
{% block head_contents %}
{% load static %}
<link href="{% static 'css/adminpage.css' %}" type="text/css" rel="stylesheet">
<meta charset="UTF-8">
{% endblock head_contents %}

{% block explain_contents %}
<style>
    .content {
        text-align :center;
        margin: 30px;
    }

    h3 {
    font-size: 30px;
    font-weight: 600;
    margin: 40px 30px 0px 100px;
    text-align: left;
    color : #FFFFFF;
    }

    h4 {
        font-size: 25px;
        font-weight: 600;
        margin: 0px 30px 0px 30px;
        text-align: center;
        color : #FFFFFF;
    }
    .content {
        text-align : center;
        padding: 5px;
    }
    .content .title{
        margin-top: 10px;
        margin-bottom: 30px;
    }
    .content .myinfo {
        border-top : 1px solid #999;
        border-bottom: 1px solid #999;
        margin: auto;
        width: 400px;
        padding-top: 10px;
        padding-bottom: 0px;
    }
    .content .myinfo dl {
        display: inline-block;
    }
    .content .myinfo dl dt, dd {
        display: inline-block;
        font-size: 14px;
    }

    .content .myinfo dl dt {
        margin-left: 5px;
        color:#999;
    }
    .content .myinfo dl dd {
        margin-right: 10px;
        margin-left: 5px;
    }
    .content .myinfo dd {
        margin-right: 10px;
        margin-left: 5px;
        color : #FFFFFF;
    }
    .cont {
        border-radius: 10px;
        margin: 30px auto; /* 수평 가운데 정렬을 위해 margin을 auto로 설정 */
        padding-bottom: 30px;
        text-align: center;
        border: 1px solid #999;
        width: 50.5%;
        max-width: 50.5%; /* 요소의 최대 너비를 100%로 설정 */
    }

    .cont p {
        margin-top: 30px;
        padding: 10px 20px 10px 20px;
        text-align: center;
        color : #FFFFFF;
    }

    .button {
        text-align: right;
        margin : 0px 200px 10px 0px;
    }

    .button button {
        text-align: right;
    }

   .answer {
    display: flex;
    flex-direction: column;
    }

    .answer input {
        width: 54%;
        max-width: 54%;
        height: 80.5%;
        padding: 10px;
        border: 1px solid #999;
        border-radius: 10px;
        margin: 10px auto;

    }

    .answer_button {
        text-align: right;
        margin : 0px 380px 0px 0px;

    }


    .button_back {
        text-align: right;
        margin: 0px 150px 0px 0px;
    }


    .button_back button{
        font-size: 11px;
    }

    .answer_button button {
        text-align: right;
        font-size: 5px;
    }

    .comment-header {
        margin-left: 380px;
        margin-right: 380px;
        border-top: 1px solid #999;
        padding-top: 5px;
        padding-bottom: 0px;
        margin-top: 20px;
        font-weight: bold;
    }

   .answer_text {
        margin: 10px 380px 25px 380px;
        border-top: 1px solid #999;
    }

    .answer-text du {
        margin : 5px 0 0 0;
        font-size: 5px;
    }

    .answer-text dd {
        font-size: 5px;
    }

    .answer-text dl {
        margin-bottom : 0px;
    }

    .answer_delete {
        margin : 0px 380px 0px 0px;
        text-align: right;
    }

    .answer_delete button {
        margin: 0 0 5px 0 ;
        font-size: 5px;
    }

    .comment-header {
        color : #FFFFFF;
    }




</style>

<h3> 질문게시판 </h3>
<div class="total">
    <div class="content">
        <div class="button_back">
            <button type="submit" name=delete class="btn btn-warning"><a
                    href="{% url 'adminpage:questionboard_index' %}" style="color: black; text-decoration: none; ">목록으로
                돌아가기</a></button>
        </div>
        <div class="title">
            <h4>제목 : {{article.title}} </h4>
        </div>
        <div class="myinfo">
            <dl>
                <dt>작성자</dt>
                <dd> {{article.username.username}}</dd>
            </dl>
            <dl>
                <dt>작성일자</dt>
                <dd> {{article.create_date}}</dd>
            </dl>
            <dl>
                <dt>조회수</dt>
                <dd> {{article.count}}</dd>
            </dl>
        </div>
        <div class="cont">
            <br>
            <p>{{article.text}} </p>
        </div>
    </div>
</div>
<div class="answer_input">
    <div class="comment-header">댓글</div>
    {% for answer in article.answer_set.all %}
    <div class="answer_text">
        <du style="color : #FFFFFF;">[{{ answer.admin_id.admin_id }}]</du>
        <dt style="color : #FFFFFF;">{{ answer.text }}</dt>
        <dd style="color : #FFFFFF;">{{ answer.create_date }}</dd>
    </div>
    <form method="POST">
        {% if user.authority == 4 or user.authority == 5 %}
        <div class="answer_delete">
            <input type="hidden" name="answer_id" value="{{ answer.id }}">
            {% csrf_token %}
            <button type="submit" name=delete class="btn btn-dark">삭제</button>
        </div>
        {% endif %}
    </form>
    {% endfor %}
</div>

<form method="POST" action="{% url 'adminpage:questionboard_detail' article.question_num %}">
    {% csrf_token %}
    {% if user.authority == 4 or user.authority == 5 %}
    <div class="answer">
        <input type="hidden" name="question_num" value="{{ article.question_num }}">
        <input type="text" placeholder="댓글을 입력하세요" name="text">
    </div>
    <div class="answer_button">
        <button type="submit" name=create class="btn btn-dark">입력</button>
    </div>
    {% endif %}
</form>

<div class="button">
    <input type="hidden" value="{{article.admin_id}}">
    <button type="submit" name=delete class="btn btn-warning"><a
            href="{% url 'adminpage:questionboard_delete' article.question_num %}"
            style="color: black; text-decoration: none; ">삭제</a></button>
</div>
{% endblock explain_contents %}

adminpage/templates/questionboardadmin/questionboard_admin_index.html
{% extends "admin_base.html" %}
{% block head_contents %}
{% load static %}
<link href="{% static 'css/adminpage.css' %}" type="text/css" rel="stylesheet">
<meta charset="UTF-8">
{% endblock head_contents %}

{% block explain_contents %}
<div class="projects mb-4">
    <div class="projects-inner">
        <header class="projects-header">
            <div class="title">질문게시판</div>
            <i class="zmdi zmdi-download"></i>
        </header>
        <table class="projects-table">
            <thead>
            <tr>
                <th>No</th>
                <th>제목</th>
                <th>작성자</th>
                <th>작성일</th>
                <th>조회수</th>
            </tr>
            </thead>
            <tbody>
            {% for article in page_obj %}
            <tr>
                <td><a href="{% url 'adminpage:questionboard_detail' article.question_num %}">{{ article.question_num }}</a></td>
                <td>{{ article.title }}</td>
                <td>{{ article.username.username }}</td>
                <td>{{ article.create_date }}</td>
                <td>{{ article.count }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <br>
    </div>
</div>


<div class="pagination">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; 처음</a>
    <a href="?page={{ page_obj.previous_page_number }}">이전</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if num == page_obj.number %}
    <span class="current-page">{{ num }}</span>
    {% else %}
    <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">다음</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">끝 &raquo;</a>
    {% endif %}
</div>
{% endblock explain_contents %}