main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('startpage.urls')),
    path('home/', include('uploadpage.urls', namespace='uploadpage')),
    path('home/', include('adminpage.urls', namespace='adminpage')),
    path('home/', include('notice.urls', namespace='notice')),
    path('home/', include('questionboard.urls', namespace='questionboard')),
    path('home/', include('labelingpage.urls', namespace='labelingpage')),
    path('home/', include('my_page.urls', namespace='my_page')),
    path('home/', include('yolov8.urls', namespace='yolov8')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questionboard/urls.py
from django.urls import path
from questionboard import views

app_name = 'questionboard'

urlpatterns = [
    path('questionboard/', views.index, name='index'),
    path('questionboard/new/', views.NewView, name='new'),
    path('questionboard/create/', views.Create, name='create'),
    path('questionboard/<int:pk>/', views.Detail, name='detail'),
    path('questionboard/<int:pk>/delete/', views.delete, name='delete'),
    path('questionboard/<int:pk>/edit/', views.edit, name='edit'),
    path('questionboard/<int:pk>/update/', views.update, name='update')
]

questionboard/models.py
from django.db import models
from Account.models import UserInfo
from adminpage.models import Admin


class QuestionBoard(models.Model):
    question_num = models.AutoField(primary_key=True)
    username = models.ForeignKey(UserInfo, on_delete=models.CASCADE, db_column='username')
    title = models.TextField()
    text = models.TextField()
    create_date = models.DateField(auto_now_add=True)
    count = models.IntegerField(null=True)

    class Meta:
        db_table = 'question_board'

    @property
    def update_counter(self):
        self.count +=1
        self.save()

class Answer(models.Model):
    admin_id = models.ForeignKey(Admin, on_delete=models.CASCADE, db_column='admin_id')
    question_num = models.ForeignKey(QuestionBoard, on_delete=models.CASCADE, db_column='question_num')
    text = models.TextField()
    create_date = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'answer'

questionboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from adminpage.models import Admin
from questionboard.models import QuestionBoard, Answer
from Account.models import UserInfo
from datetime import datetime, timedelta
from django.urls import reverse
from django.core.paginator import Paginator

id=1
def index(request):
    articles = QuestionBoard.objects.order_by('-question_num')
    user = request.user.username
    username = UserInfo.objects.get(username=user)

    # 페이징
    paginator = Paginator(articles, 7)  # 페이지당 5개의 게시물
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'authority': username.authority
    }
    return render(request, 'questionboard/index.html', context)
def NewView(request):
    return render(request, 'questionboard/qutionboard_new.html')

def Create(request):
    title = request.GET.get('title')
    text = request.GET.get('text')
    create_date = request.GET.get('create_date')
    username = request.user.username
    user_info = UserInfo.objects.get(username=username)
    count = 0
    username = user_info
    article = QuestionBoard(title=title, text=text, count=count, username=username, create_date=create_date)
    article.save()

    return redirect('/home/questionboard/')

def increase_id():
    last_answer = Answer.objects.last()
    if last_answer:
        return last_answer.id + 1
    else:
        return 1

def Detail(request, pk):
    article = QuestionBoard.objects.get(pk=pk)
    username = request.user.username
    user = UserInfo.objects.get(username=username)

    context = {
        'authority': user.authority,
        'user': user,
        'article': article,
    }
    print(user.username)

    if request.method == 'POST':
        if 'create' in request.POST:
            # 댓글 작성 코드
            create_date = request.POST.get('create_date')
            username = request.user.username
            user = UserInfo.objects.get(username=username)
            admin_id = Admin.objects.get(admin_id=user.username)
            text = request.POST.get('text')

            answer_make = Answer.objects.create(
                question_num=QuestionBoard.objects.get(pk=pk),
                text=text,
                create_date=create_date,
                admin_id=admin_id
            )
            answer_make.save()

            return redirect(f'/home/questionboard/{article.pk}/')

        elif 'delete' in request.POST:
            # 댓글 삭제 코드
            answer_id = request.POST.get('answer_id')
            answer = Answer.objects.get(id=answer_id)
            answer.delete()
            return redirect(f'/home/questionboard/{article.pk}/')

    else:
        # GET 요청 처리
        cookie_value = request.COOKIES.get('count', '_')

        if f'_{pk}_' not in cookie_value:
            cookie_value += f'{pk}_'
            expire_date = datetime.now() + timedelta(days=1)
            expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
            max_age = (expire_date - datetime.now()).total_seconds()

            # 쿠키 설정
            response = render(request, 'questionboard/detail.html', context)
            response.set_cookie('count', value=cookie_value, max_age=max_age, httponly=True)

            # 조회수 증가
            article.count += 1
            article.save()

            return response

    return render(request, 'questionboard/detail.html', context)


def edit(request, pk):
    article = QuestionBoard.objects.get(pk=pk)

    context = {
        'article' : article
    }
    return render(request, 'questionboard/edit.html', context)

def update(request,pk):
    article = QuestionBoard.objects.get(pk=pk)

    title = request.GET.get('title')
    text = request.GET.get('text')

    article.title = title
    article.text = text

    article.save()

    return redirect(f'/home/questionboard/{article.pk}/')

def delete(request, pk):
    article = QuestionBoard.objects.get(pk=pk)
    article.delete()

    return redirect('/home/questionboard/')


def detail_answer(request, pk):
    article = QuestionBoard.objects.get(question_num=pk)
    context = {
        'article': article
    }
    return render(request, 'questionboard/detail.html', context)

def Create_answer(request):
    question_num = request.POST.get('question_num')
    text = request.POST.get('text')
    create_date = request.POST.get('create_date')
    admin_id = Admin.objects.get(admin_id='whalwjd')
    articles = QuestionBoard(text=text, admin_id=admin_id, creat_date=create_date, question_num=question_num)
    articles.save()

    return redirect('questionboard:detail')

questionboard/templates/questionboard/detail.html
{% extends "base2.html" %}
{% load static %}
{% block explain_contents %}
<style>


    .content {
        text-align :center;
        margin: 30px;
        }
    h3 {
    font-size: 30px;
    font-weight: 600;
    margin: 40px 30px 0px 100px;
    text-align: left;
}
   h4 {
        font-size: 25px;
        font-weight: 600;
        margin: 0px 30px 0px 30px;
        text-align: center;
}
    .content {
        text-align : center;
        padding: 5px;
}
    .content .title{
        margin-top: 10px;
        margin-bottom: 30px;
}
    .content .myinfo {
        border-top : 1px solid #999;
        border-bottom: 1px solid #999;
        margin: auto;
        width: 400px;
        padding-top: 10px;
        padding-bottom: 0px;
}
    .content .myinfo dl {
        display: inline-block;
}
    .content .myinfo dl dt, dd{
        display: inline-block;
        font-size: 14px;
}

    .content .myinfo dl dt{
        margin-left: 5px;
        color:#999;
}
    .content .myinfo dl dd{
        margin-right: 10px;
        margin-left: 5px;
}
    .cont {
        border-radius: 10px;
        margin: 30px auto; /* 수평 가운데 정렬을 위해 margin을 auto로 설정 */
        padding-bottom: 30px;
        text-align: center;
        border: 1px solid #999;
        width: 50.5%;
        max-width: 50.5%; /* 요소의 최대 너비를 100%로 설정 */
}
    .cont p{
        margin-top: 30px;
        padding: 10px 20px 10px 20px;
        text-align: center;

}
    .button {
        text-align: right;
        margin : 0px 200px 10px 0px;
}

    .button button {
        text-align: right;
}
   .answer {
    display: flex;
    flex-direction: column;
}

    .answer input {
        width: 50%;
        max-width: 50%;
        height: 80.5%;
        padding: 10px;
        border: 1px solid #999;
        border-radius: 10px;
        margin: 10px auto;

    }

    .answer_button {
        text-align: right;
        margin : 0px 480px 0px 0px;

}


    .button_back {
        text-align: right;
        margin : 0px 150px 0px 0px;
}


    .button_back button{
        font-size: 11px;

}
    .answer_button button {
        text-align: right;
        font-size: 5px;
}
    .comment-header {
        margin-left: 480px;
        margin-right: 480px;
        border-top: 1px solid #999;
        padding-top: 5px;
        padding-bottom: 0px;
        margin-top: 20px;
        font-weight: bold;
    }
   .answer_text {
        margin: 10px 480px 25px 480px;
        border-top: 1px solid #999;
    }
    .answer-text du {
        margin : 5px 0px 0px 0px;
        font-size: 5px;
    }
    .answer-text dd {
        font-size: 5px;
    }
    .answer-text dl {
        margin-bottom : 0px;
    }
    .answer_delete {
        margin : 0px 480px 0px 0px;
        text-align: right;
    }
    .answer_delete button {
        margin: 0px 0px 5px 0px ;
        font-size: 5px;
    }
</style>

<h3> 질문게시판 </h3>
<div class="total">
   <div class="content">
        <div class="button_back">
            <button type="submit" name = delete  class="btn btn-warning"><a href="{% url 'questionboard:index' %}" style="color: black; text-decoration: none; ">목록으로 돌아가기</a></button>
        </div>
       <div class="title">
        <h4>제목 : {{article.title}} </h4>
       </div>
       <div class="myinfo">
           <dl>
               <dt>작성자</dt>
               <dd> {{article.username.username}} </dd>
           </dl>
           <dl>
               <dt>작성일자</dt>
               <dd> {{article.create_date}} </dd>
           </dl>
           <dl>
               <dt>조회수</dt>
               <dd> {{article.count}} </dd>
           </dl>
       </div>
       <div class="cont">
           <br>
           <p>{{article.text}} </p>
       </div>
   </div>
</div>
<div class="answer_input">
    <div class="comment-header">댓글</div>
        {% for answer in article.answer_set.all %}
        <div class = "answer_text">
            <du>[{{ answer.admin_id.admin_id }}]</du>
            <dt>{{ answer.text }}</dt>
            <dd>{{ answer.create_date }}</dd>
        </div>
    {% endfor %}
</div>
       <form method="POST" action="{% url 'questionboard:detail' article.question_num %}">
       </form>
{% if user.authority == 4 or user.authority == 5 or user.username == article.username.username %}
<div class="button">
    <input type="hidden" value="{{article.admin_id}}">
    <button type="submit" name = revise  class="btn btn-warning"><a href="{% url 'questionboard:edit' article.question_num %}" style="color: black; text-decoration: none; ">수정</a></button>
    <input type="hidden" value="{{article.admin_id}}">
    <button type="submit" name = delete  class="btn btn-warning"><a href="{% url 'questionboard:delete' article.question_num %}" style="color: black; text-decoration: none; ">삭제</a></button>
</div>
{% endif %}


{% endblock explain_contents %}

questionboard/templates/questionboard/edit.html
{% extends "base2.html" %}
{% load static %}
{% block explain_contents %}
<style>
h3 {
    font-size: 30px;
    font-weight: 600;
    margin: 40px 30px 10px 30px;
}

 form {
   text-align: center;
}


.card-write{
    padding: 20px;
}
.card-write input, textarea{
    margin-left: 10px;
    padding: 10px;
    border: 1px solid #999;
    border-radius:10px;
    box-shadow: 3px 3px 1-px #e6e6e6;
}
.card-write .title input {
    margin-top: 20px;
    margin-bottom : 20px;
    width: 50.5%;
}
.card-write .content textarea {
     min-width : 50.5%;
     max-width : 50.5%;
     min-height: 300px;
     max-height: 00px;
     box-shadow: inset 3px 3px 10px #e6e6e6;
     vertical-align: top;
}
.button {
    text-align: right;
    margin: 30px 150px 10px 0px;
}

.button button {
  margin-right : 5px;
}
</style>
<div>
  <div class="card-write">
    <form action="{% url 'questionboard:update' pk=article.pk %}">
      <div class="card-write">
        <h3>질문게시판</h3>
        <div class="card-edit">
          <div class="title">
            제목 <input type="text" name="title" value="{{article.title}}">
          </div>
          <div class="content">
            내용 <textarea name="text">{{article.text}}</textarea>
          </div>
        </div>
        <div class="button">
          <input type="hidden" value="{{article.question_num}}">
          <button type="submit" name="create" class="btn btn-warning">
            <a href="{% url 'questionboard:update' pk=article.pk %}" style="color: black; text-decoration: none;">수정</a>
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock explain_contents %}

questionboard/templates/questionboard/index.html
{% extends "base2.html" %}
{% load static %}

{% block explain_contents %}
<style>
    h3 {
        margin: 30px;
    }
    .pagination {
        margin-top: 20px;
        display: flex;
        justify-content: center;
    }
    .pagination a, .pagination span {
        margin-right: 10px; /* 원하는 간격으로 조정 */
    }


    table {
        border-spacing: 1px;
        border-collapse: collapse;
        background: white;
        border-radius: 6px;
        overflow: hidden;
        width: 100%;
        margin: 0 auto;
        position: relative;
    }
    table * {
        position: relative;
    }
    table td, table th {
        padding-left: 8px;
        text-align: center; /* 가운데 정렬 추가 */
    }
    table thead tr {
        height: 60px;
        background: #F2CB61;
        font-size: 16px;
    }
    table tbody tr {
        height: 48px;
        border-bottom: 1px solid #E3F1D5;
    }
    table tbody tr:last-child {
        border: 0;
    }

    @media screen and (max-width: 35.5em) {
        table {
            display: block;
        }
        table > *,
        table tr,
        table td,
        table th {
            display: block;
        }
        table thead {
            display: none;
        }
        table tbody tr {
            height: auto;
            padding: 8px 0;
        }
        table tbody tr td {
            padding-left: 45%;
            margin-bottom: 12px;
        }
        table tbody tr td:last-child {
            margin-bottom: 0;
        }
        table tbody tr td:before {
            position: absolute;
            font-weight: 700;
            width: 40%;
            left: 10px;
            top: 0;
        }
        table tbody tr td:nth-child(1):before {
            content: "CODE";
        }
        table tbody tr td:nth-child(2):before {
            content: "STOCK";
        }
        table tbody tr td:nth-child(3):before {
            content: "CAP";
        }
        table tbody tr td:nth-child(4):before {
            content: "INCH";
        }
        table tbody tr td:nth-child(5):before {
            content: "BOX TYPE";
        }
    }
</style>

<div class="container">
    <h3>질문게시판</h3><br>
    <table>
        <thead>
        <tr>
            <th>No</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일</th>
            <th>조회수</th>
        </tr>
        </thead>
        <tbody>
        {% for article in page_obj %}
        <tr>
            <td>{{ article.question_num }}</a></td>
            <td><a style="color:#000000" href="{% url 'questionboard:detail' article.question_num %}">{{ article.title }}</td>
            <td>{{ article.username.username }}</td>
            <td>{{ article.create_date }}</td>
            <td>{{ article.count }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <br>
    {% if user.is_authenticated %}
    <div align="right">
        <button type="button" class="btn btn-warning"><a href="{% url 'questionboard:new' %}"
                                                         style="color: black; text-decoration: none;">질문작성</a></button>
    </div>
    {% endif %}
</div>
<br>

<!-- 페이지 번호 표시 -->
<div class="pagination">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; 처음</a>
    <a href="?page={{ page_obj.previous_page_number }}">이전</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if num == page_obj.number %}
    <span class="current-page">{{ num }}</span>
    {% else %}
    <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">다음</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">끝 &raquo;</a>
    {% endif %}
</div>

{% endblock explain_contents %}

questionboard/templates/questionboard/qutionboard_new.html
{% extends "base2.html" %}
{% load static %}
{% block explain_contents %}
<style>

h3 {
    font-size: 30px;
    font-weight: 600;
    margin: 40px 30px 0px 30px;
}

 form {
   text-align: center;
}


.card-write{
    padding: 20px;
}
.card-write input, textarea{
    margin-left: 10px;
    padding: 10px;
    border: 1px solid #999;
    border-radius:10px;
    box-shadow: 3px 3px 1-px #e6e6e6;
}
.card-write .title input {
    margin-top: 20px;
    margin-bottom : 20px;
    width: 50.5%;
}
.card-write .content textarea {
     min-width : 50.5%;
     max-width : 50.5%;
     min-height: 300px;
     max-height: 00px;
     box-shadow: inset 3px 3px 10px #e6e6e6;
     vertical-align: top;
}
.button {
    text-align: right;
}

.button button {
  margin-right : 120px;
}
</style>
<form action= "{% url 'questionboard:create' %}" >
    <div>
    <h3> 질문게시판 </h3>
        <div class = "card-write">
            <div class="title">
                제목 <input placeholder="제목을 입력하세요" type="text" name="title">
            </div>
            <div class="content">
                내용 <textarea placeholder="내용을 입력하세요" name="text"></textarea>
            </div>
        </div>
        <div class ="button">
            <input type="hidden" value="{{article.question_num}}">
            <button type="submit" name = create class="btn btn-warning"><a href="/home/questionboard" style="color: black; text-decoration: none;">작성</a></button>
        </div>
    </div>
</form>
{% endblock explain_contents %}